/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlinBasics2

class App {

}
fun max(a: Int,b:Int): Int{
    val another = "one"
    val age = 63;
    var secondAge: Int = 33
    return if(a>b) a else b
}
fun max2(a:Int,b:Int) = if(a > b) a else b

fun main() {
    println(max2(2,3))
}
